FROM python:3.8-slim
#RUN pip3 install pip --upgrade
RUN pip3 install --no-cache-dir flask flask_sqlalchemy requests prometheus-client prometheus_flask_exporter
COPY . /app
WORKDIR /app
CMD python3 app.py
