# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/contrib-buster64"
  config.vm.box_url = "https://app.vagrantup.com/debian/boxes/contrib-buster64/versions/10.20211018.1/providers/virtualbox.box"

  config.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 8
  end
  config.vm.box_check_update = false
  config.vm.provision "shell", inline: "mkdir /root/.ssh/ && cat /vagrant/ansible.pub >> /root/.ssh/authorized_keys && cat /vagrant/ansible.pub >> /home/vagrant/.ssh/authorized_keys"
  # vagrant_ssh_username
  config.ssh.username = "vagrant"

# Single host web01
  config.vm.define "web01" do |web01|
    web01.vm.network :forwarded_port, guest: 22, host: 2202, id: "ssh"
    web01.vm.network :forwarded_port, guest: 5000, host: 5000, id: "flask"
    web01.vm.network "private_network", ip: '192.168.200.101', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "cluster00" # to cluster00
    web01.vm.hostname = "web01.lab"
  end

config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vvv"
    ansible.playbook = "Playbook.yml"
    # Ansible_ssh_user
    ansible.force_remote_user = "vagrant"
    ansible.become = "true"
    ansible.inventory_path = "./inventory"
    ansible.raw_arguments = [
      "--connection=paramiko",
      "--private-key=./ansible"
    ]
  end
end