apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring 
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.project.local
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: stable-grafana
                port:
                  number: 80
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
  #  tls:
    #    - hosts:
      #      - www.example.com
        #      secretName: example-tls
